### ISSUE TITLE
availability of location information is interrupted when rotating the device

### ISSUE THREAD

**Issue by wuan** [wuan/bo-android#129] opened 2016-05-08 22:36 UTC
We could have a short lived cache to keep location information while rotating the device. Sometimes it takes several seconds until the location is fixed after rotation.

**Comment by d3xter** [comment] 2016-05-09 06:55
This is already fixed on the 1.6 branch. The problem is, that when rotating the screen, the LocationHandler sends out a NULL-Location to all clients.

When Main reattaches to Location-Updates it receives the last NULL location.

**Closed** 2016-05-10 20:02 UTC
Labels: BUG
